import type { Project, Founder } from "../types"

// Mock Projects Data
export const mockProjects: Project[] = [
  {
    id: "1",
    title: "EcoTrack",
    slug: "ecotrack",
    description: "A mobile app that helps consumers track and reduce their carbon footprint through daily choices.",
    longDescription:
      "EcoTrack uses machine learning to analyze user behavior and suggest personalized ways to reduce environmental impact. The app connects to smart home devices, tracks transportation choices, and provides insights on shopping habits to help users make more sustainable choices.",
    founder: "alex_green",
    founderName: "Alex Green",
    score: 87,
    tags: ["sustainability", "mobile", "ai"],
    createdAt: "2025-06-15T10:30:00Z",
  },
  {
    id: "2",
    title: "MediSync",
    slug: "medisync",
    description: "Healthcare platform connecting patients with their medical records across different providers.",
    longDescription:
      "MediSync solves the fragmentation problem in healthcare by creating a unified patient record that can be securely shared between providers. Using blockchain for security and AI for insights, the platform helps reduce medical errors and improves care coordination.",
    founder: "sarah_johnson",
    founderName: "Sarah Johnson",
    score: 92,
    tags: ["health", "blockchain", "saas"],
    createdAt: "2025-06-10T14:20:00Z",
  },
  {
    id: "3",
    title: "CodeBuddy",
    slug: "codebuddy",
    description: "AI-powered coding assistant that helps developers write better code faster.",
    longDescription:
      "CodeBuddy uses advanced AI models to understand codebases and suggest improvements, detect bugs before they happen, and automate repetitive coding tasks. The tool integrates with all major IDEs and supports over 20 programming languages.",
    founder: "mike_dev",
    founderName: "Mike Dev",
    score: 78,
    tags: ["developer-tools", "ai", "productivity"],
    createdAt: "2025-06-05T09:15:00Z",
  },
  {
    id: "4",
    title: "UrbanFarm",
    slug: "urbanfarm",
    description: "Vertical farming solution for urban environments to grow fresh produce locally.",
    longDescription:
      "UrbanFarm designs modular vertical farming units that can be installed in urban buildings, allowing communities to grow fresh produce year-round regardless of climate. The system uses 95% less water than traditional farming and eliminates the need for pesticides.",
    founder: "lisa_wong",
    founderName: "Lisa Wong",
    score: 81,
    tags: ["agriculture", "sustainability", "hardware"],
    createdAt: "2025-06-01T11:45:00Z",
  },
  {
    id: "5",
    title: "FinLit",
    slug: "finlit",
    description: "Financial literacy platform that gamifies learning about personal finance and investing.",
    longDescription:
      "FinLit makes financial education engaging through interactive simulations, challenges, and personalized learning paths. Users can practice investing with virtual money, learn budgeting skills, and earn rewards for developing healthy financial habits.",
    founder: "james_smith",
    founderName: "James Smith",
    score: 73,
    tags: ["education", "fintech", "mobile"],
    createdAt: "2025-05-28T16:30:00Z",
  },
  {
    id: "6",
    title: "RemoteTeams",
    slug: "remoteteams",
    description: "All-in-one platform for managing distributed teams and enhancing remote collaboration.",
    longDescription:
      "RemoteTeams combines project management, communication, and HR tools specifically designed for remote-first companies. The platform includes features for virtual team building, asynchronous workflows, and measuring team wellbeing and productivity.",
    founder: "elena_garcia",
    founderName: "Elena Garcia",
    score: 85,
    tags: ["productivity", "remote-work", "saas"],
    createdAt: "2025-05-25T13:10:00Z",
  },
  {
    id: "7",
    title: "SecureVote",
    slug: "securevote",
    description: "Blockchain-based voting system for secure and transparent elections.",
    longDescription:
      "SecureVote uses blockchain technology to create a tamper-proof voting system that ensures vote integrity while maintaining voter privacy. The platform can be used for national elections, corporate governance, or community decision-making.",
    founder: "david_kim",
    founderName: "David Kim",
    score: 68,
    tags: ["blockchain", "govtech", "security"],
    createdAt: "2025-05-20T10:00:00Z",
  },
  {
    id: "8",
    title: "PetPal",
    slug: "petpal",
    description: "Smart pet care system that monitors pet health and automates feeding schedules.",
    longDescription:
      "PetPal combines IoT devices and a mobile app to help pet owners take better care of their animals. The system includes smart feeders, health monitors, and AI-powered behavior analysis to detect potential health issues early.",
    founder: "olivia_patel",
    founderName: "Olivia Patel",
    score: 76,
    tags: ["iot", "consumer", "pets"],
    createdAt: "2025-05-15T15:40:00Z",
  },
  {
    id: "9",
    title: "LegalEase",
    slug: "legalease",
    description: "AI legal assistant that makes legal services more accessible and affordable.",
    longDescription:
      "LegalEase uses natural language processing to help people navigate common legal issues without expensive attorney fees. The platform can generate custom legal documents, answer questions about legal processes, and connect users with affordable legal professionals when needed.",
    founder: "marcus_johnson",
    founderName: "Marcus Johnson",
    score: 82,
    tags: ["legal", "ai", "saas"],
    createdAt: "2025-05-10T09:20:00Z",
  },
  {
    id: "10",
    title: "ArtBlock",
    slug: "artblock",
    description: "NFT marketplace for digital artists with built-in copyright protection.",
    longDescription:
      "ArtBlock helps digital creators monetize their work through NFTs while providing tools to protect their intellectual property. The platform includes features for royalty management, authentication of original works, and connecting artists with collectors.",
    founder: "zoe_chen",
    founderName: "Zoe Chen",
    score: 79,
    tags: ["nft", "blockchain", "creative"],
    createdAt: "2025-05-05T12:50:00Z",
  },
  {
    id: "11",
    title: "FoodRescue",
    slug: "foodrescue",
    description: "Platform connecting restaurants with excess food to local shelters and food banks.",
    longDescription:
      "FoodRescue tackles food waste and hunger simultaneously by creating an efficient logistics network for food donation. Restaurants and grocery stores can easily donate surplus food, which is quickly matched with nearby organizations that can distribute it to those in need.",
    founder: "ryan_patel",
    founderName: "Ryan Patel",
    score: 88,
    tags: ["social-impact", "food", "logistics"],
    createdAt: "2025-05-01T14:15:00Z",
  },
  {
    id: "12",
    title: "MindfulWork",
    slug: "mindfulwork",
    description: "Workplace wellness platform that helps prevent burnout and improve mental health.",
    longDescription:
      "MindfulWork integrates with workplace tools to detect signs of stress and burnout, then provides personalized interventions. The platform includes guided meditation, work-life balance coaching, and analytics for HR teams to improve organizational wellbeing.",
    founder: "tara_williams",
    founderName: "Tara Williams",
    score: 84,
    tags: ["health", "hr", "wellness"],
    createdAt: "2025-04-25T11:30:00Z",
  },
]

// Mock Founders Data
export const mockFounders: Founder[] = [
  {
    id: "1",
    name: "Alex Green",
    headline: "Sustainability Entrepreneur | Former Tesla Engineer",
    avatar: "",
    ideas: 3,
    averageScore: 87,
  },
  {
    id: "2",
    name: "Sarah Johnson",
    headline: "Healthcare Innovator | MD/MBA",
    avatar: "",
    ideas: 2,
    averageScore: 92,
  },
  {
    id: "3",
    name: "Mike Dev",
    headline: "Full-Stack Developer | AI Enthusiast",
    avatar: "",
    ideas: 4,
    averageScore: 78,
  },
  {
    id: "4",
    name: "Lisa Wong",
    headline: "AgTech Pioneer | Environmental Scientist",
    avatar: "",
    ideas: 1,
    averageScore: 81,
  },
  {
    id: "5",
    name: "James Smith",
    headline: "FinTech Founder | Former JP Morgan",
    avatar: "",
    ideas: 2,
    averageScore: 73,
  },
  {
    id: "6",
    name: "Elena Garcia",
    headline: "Remote Work Advocate | Ex-Gitlab",
    avatar: "",
    ideas: 3,
    averageScore: 85,
  },
  {
    id: "7",
    name: "David Kim",
    headline: "Blockchain Developer | Cybersecurity Expert",
    avatar: "",
    ideas: 2,
    averageScore: 68,
  },
  {
    id: "8",
    name: "Olivia Patel",
    headline: "IoT Specialist | Animal Lover",
    avatar: "",
    ideas: 1,
    averageScore: 76,
  },
  {
    id: "9",
    name: "Marcus Johnson",
    headline: "Legal Tech Innovator | JD/MBA",
    avatar: "",
    ideas: 2,
    averageScore: 82,
  },
  {
    id: "10",
    name: "Zoe Chen",
    headline: "Digital Artist | Web3 Entrepreneur",
    avatar: "",
    ideas: 3,
    averageScore: 79,
  },
  {
    id: "11",
    name: "Ryan Patel",
    headline: "Social Entrepreneur | Food Industry Veteran",
    avatar: "",
    ideas: 1,
    averageScore: 88,
  },
  {
    id: "12",
    name: "Tara Williams",
    headline: "Workplace Psychologist | Wellness Coach",
    avatar: "",
    ideas: 2,
    averageScore: 84,
  },
  {
    id: "13",
    name: "Carlos Rodriguez",
    headline: "EdTech Founder | Former Google Education",
    avatar: "",
    ideas: 3,
    averageScore: 81,
  },
  {
    id: "14",
    name: "Aisha Khan",
    headline: "AI Researcher | PhD in Machine Learning",
    avatar: "",
    ideas: 2,
    averageScore: 90,
  },
  {
    id: "15",
    name: "Noah Wilson",
    headline: "Climate Tech Innovator | Renewable Energy Expert",
    avatar: "",
    ideas: 4,
    averageScore: 86,
  },
]
